### ISSUE TITLE
Unclear how to scroll the list of examples

### ISSUE THREAD

**Issue by fson** [expo/create-react-native-app#816]
**Describe the bug**

When choosing a template, I couldn't find a way to scroll the list of templates past the page 1 out of 3.

**To Reproduce**
1. Run `npx create-react-native-app`
2. `How would you like to start`: Choose `› Template from expo/examples`
3. `Pick an example`: you see 10 template names, and can move between them with up/down arrow keys, but the remaining 18 are hidden. Scrolling to the end of the list doesn't reveal more. Also tried `left`/`right`, `PgDn`.

**Expected behavior**

Allow seeing all templates or at least no "Page 1/3" shown if there are no more pages to see.

**Screenshots**

<img width="922" alt="Screen Shot 2020-05-22 at 15 21 04" src="https://user-images.githubusercontent.com/497214/82674522-1ad78180-9c4c-11ea-9751-f9230e5c2189.png">

**Desktop (please complete the following information):**
- macOS 10.15.4
- Terminal.app

**Comment by arpitBhalla** [comment]
Use Page Down

**Comment by valstu** [comment]
Noticed the same but figured out that <kbd>fn</kbd> + <kbd>Key Down</kbd> worked for me (Mac OS)

**Comment by brentvatne** [comment]
tab also works

**Comment by nomi9995** [comment]
@brentvatne I have fix scroll in the list of examples. now users can scroll by arrow keys. you can review my PR #846

**Comment by byCedric** [comment]
I think this is resolved in `prompts` itself now, starting from version `2.3.1` (https://github.com/terkelg/prompts/pull/230) cc @fson

**Comment by nomi9995** [comment]
<img width="504" alt="Screenshot 2020-08-12 at 4 47 59 PM" src="https://user-images.githubusercontent.com/36044436/90011764-9d0b9b00-dcbb-11ea-9823-0ea1f32aaacd.png">
@byCedric it was merge `7 Nov 2019` and not resolved. user have to go to next page by `tab` or `fn + ▼`. but in my pull request #846 i have patched. now user can scroll by arrow keys simple

**Comment by byCedric** [comment]
@nomi9995 yes, but why don't we use that version `2.3.2` in our project instead of creating (and maintaining) a patch on our own? 😄  It works pretty good with `prompts@2.3.2`, I added a gif of what's happening with this update. I didn't change anything else.

![Screen Recording 2020-08-12 at 14 09 00](https://user-images.githubusercontent.com/1203991/90013581-d5a07a00-dca5-11ea-98f4-ec752c1a2a96.gif)

**Comment by nomi9995** [comment]
yeah, you are right. I also tested 2.3.2 but I don't know why it did not work on my side 😄
